In [20]:
import numpy as np

1차원 생성하기

In [21]:
array1 = np.array([1,2,3])
print(array1)
print(type(array1))
print(array1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


2차원 생성하기

In [22]:
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)
print(type(array2))
print(array2.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [23]:
array3 = np.array([[1,2,3]])
print(array3)
print(type(array3))
print(array3.shape)

[[1 2 3]]
<class 'numpy.ndarray'>
(1, 3)


In [24]:
print('array1의 차원 :',array1.ndim,'array2의 차원 :' ,array2.ndim,'array3의 차원 :',array3.ndim)

array1의 차원 : 1 array2의 차원 : 2 array3의 차원 : 2


In [25]:
list = [1,2,3]
print(  type(list) ) 
array = np.array(list)
print( type(array) ) 
print(array.dtype)

<class 'list'>
<class 'numpy.ndarray'>
int32


In [26]:
list2 = [1,2,3,'4']
array2 = np.array(list2)
print(array2)
print(array2.dtype)   

['1' '2' '3' '4']
<U11


In [27]:
list3 = [1,2,3.14]
array3 = np.array(list3)
print(array3)
print(array3.dtype)
print(array3[0])

[1.   2.   3.14]
float64
1.0


astype 함수 사용해보기

In [28]:
array4 = array3.astype(int)
print(array4)
print(array4.dtype)

[1 2 3]
int32


arange,zeors,ones 함수 사용해보기

In [29]:
seq = np.arange(10)
print(seq)
print(seq.dtype)
print(seq.shape)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)


In [30]:
zreo_array = np.zeros((3,2), dtype= 'int32')
print(zreo_array)
print(zreo_array.dtype)
print(zreo_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32
(3, 2)


In [31]:
one_array = np.ones((2,3), dtype= 'int32')
print(one_array)
print(one_array.dtype)
print(one_array.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


차원과 크기를 변경하는 reshape

In [32]:
array1 = np.arange(10)
array2 = array1.reshape((2,5))
print(array1)
print(array1.ndim)
print(array2)
print(array2.shape)
print(array2.ndim)
array3 = array1.reshape((5,2))
print(array3)
# array4 = array1.reshape((4,3))

[0 1 2 3 4 5 6 7 8 9]
1
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [33]:
array1 = np.arange(10)
array2 = array1.reshape((-1,5))
print(array1)
print(array1.ndim)
print(array2)
print(array2.shape)
print(array2.ndim)
array3 = array1.reshape((-1,2))
print(array3)

[0 1 2 3 4 5 6 7 8 9]
1
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


인덱싱과 슬라이싱  

In [34]:
# 단일값 추출 
array = np.arange(start= 0,
    stop= 10)
print(array)
value = array[3]
print(value)
print(type(value))

[0 1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>


In [35]:
array1D = np.arange(start= 0,stop= 9)
print(array1D)
array2D = array1D.reshape((3,3))
print(array2D)
# 2차원[행,열]
print(array2D[0,0])
print(array2D[1,2])
print(array2D[2,1])

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
5
7


In [36]:
# 슬라이싱
array = np.arange(start= 0,stop= 10)
print(array[0:2])
print(array[2:5])
print(array[:5])
print(array[5:])
print(array[:])

[0 1]
[2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [37]:
# 팬시 인덱싱
array = np.arange(start= 0,stop= 10)
array2D = array.reshape((2,5))
print(array2D)
print(array2D[[0,1],2])
print(array2D[[0,1],0:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[2 7]
[[0 1]
 [5 6]]


In [38]:
# 불린 인덱싱
array = np.array([1,2,3,4,5,3,3])
array[array == 3] = 10
print(array)

# 리스트
list = [1,2,3,4,5,3,3]
list[list != 3] = 10
print(list)

# 조건문
array = np.arange(start= 0,stop= 10)
array>5
array[array > 5]

[ 1  2 10  4  5 10 10]
[1, 10, 3, 4, 5, 3, 3]


array([6, 7, 8, 9])

행렬 정렬 sort(), argsort() 

In [40]:
org_array = np.array([3,1,9,5])
# np.sort로 정렬
print(org_array)
org_array1 = np.sort(org_array)
print(org_array1)
# 내림차순
org_desc = np.sort(org_array)[::-1]
org_desc

[3 1 9 5]
[1 3 5 9]


array([9, 5, 3, 1])

In [43]:
array2D = np.array([[8,12],
                    [7,1]])
print(array2D)
sort_array2D_axis0 = np.sort(array2D,axis=0) 
print(sort_array2D_axis0)
sort_array2D_axis1 = np.sort(array2D,axis=1)
print(sort_array2D_axis1)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [44]:
org_array = np.array([3,1,9,5])
print(org_array)
sort_indices = np.argsort(org_array)
print(sort_indices)

[3 1 9 5]
[1 0 3 2]
